'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { QRScanner } from '@/components/ui/qr-scanner';
import { Camera } from 'lucide-react';
import { toast } from 'sonner';
import { uploadMatchScoutData } from './upload-action';

export function ScanQR() {
  const [open, setOpen] = useState(false);
  const [isUploading, setIsUploading] = useState(false);

  const handleScanSuccess = async (decodedText: string) => {
    try {
      setIsUploading(true);
      const data = JSON.parse(decodedText);
      
      // Basic validation to ensure it's the expected match scout data
      if (!data.eventId || !data.teamId || !data.matchSetup) {
        throw new Error("Invalid QR code data format");
      }
      
      await uploadMatchScoutData(data);
      toast.success(`Successfully uploaded match ${data.matchSetup.matchKey} for team ${data.teamId.replace('frc', '')}`);
      setOpen(false);
    } catch (err: any) {
      toast.error(`Error uploading data: ${err.message}`);
      // Note: we don't close the modal on error, allowing them to try scanning again if they wish.
      // But we would need to resume the scanner if we paused it. 
      // The QRScanner component currently pauses on success, so we might need a way to resume it or 
      // just let the user close and reopen the dialog.
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger render={
        <Button variant="outline" className="flex gap-2">
          <Camera className="w-4 h-4" />
          <span className="hidden sm:inline">Scan QR</span>
        </Button>
      } />
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Scan Match QR Code</DialogTitle>
        </DialogHeader>
        <div className="flex flex-col items-center justify-center p-2">
          {open && !isUploading && (
            <QRScanner onScanSuccess={handleScanSuccess} />
          )}
          {isUploading && (
            <div className="p-8 text-center text-muted-foreground animate-pulse">
              Uploading scanned match data...
            </div>
          )}
          <p className="text-sm text-center text-muted-foreground mt-4">
            Scan a QR code generated by another device to upload its match data to the database.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
}
